### ISSUE TITLE
Adaptación del módulo de notificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/notificacion_mid#14]
Implementar el módulo de notificaciones a nivel externo (notificaciones mediante correo electrónico) e interno (notificaciones entre usuarios).

**Criterios de aceptación**

- [x] Commit con cambios realizados.
- [x] Pruebas funcionales.

**Comment by JuanCamiloMartinezLopez** [comment]
### Documento pruebas funcionales.

Se añade el documento de la pruebas funcionales realizadas sobre el sistema de cumplidos
[Aplicación pruebas Funcionales y de Usabilidad - Notificaciones.pdf](https://github.com/udistrital/notificacion_mid/files/7850955/Aplicacion.pruebas.Funcionales.y.de.Usabilidad.-.Notificaciones.pdf)

### Commits implementacion

Se adjuntan los commits donde se hizo la implementacion de las diferentes funcionalidades.

- udistrital/cumplidos_cliente@4ef3b75
- udistrital/cumplidos_cliente@d20fc2d2e81f31583c9a5b968ef1a8adee91e95d
- udistrital/cumplidos_cliente@0c2b7528ca1b24476da557ab6b728a1ec320b871
- udistrital/cumplidos_cliente@996e5f8b6a350d8450c279f9839323d1eee04006
