### ISSUE TITLE
Documentación - Módulo de notificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/notificacion_mid#2]
Registrar documentación asociada al módulo de novedades.

Se debe tener en cuenta la guía para integración con cualquier sistema y demás elementos claves que sean necesarios

**Criterio de aceptación**

- [x] Documentación de API MID y servicios en AWS.

**Comment by FelipeVel** [comment]
Se adjunta la [documentacion](https://drive.google.com/file/d/1ZlXdKAyooyftamyCZX8Btmd5nhDR5YEX/view?usp=sharing) del api en desarrollo de notificaciones.

**Comment by a52290451** [comment]
Se valida documentación presentada
