### ISSUE TITLE
Despliegue del Módulo de notificaciones en Pruebas y producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/notificacion_mid#3]
Realizar el despliegue del API notificaciones_mid en ambiente de pruebas y producción, teniendo en cuenta el Check-list requerido para tal fin.

**Criterios de aceptación**

- [x] Check-list
- [x] Despliegue en ambiente de pruebas
- [x] Despliegue en ambiente de producción

**Comment by FelipeVel** [comment]
Se añade el [checklist](https://docs.google.com/document/d/1IuN2zEyuU7O9LsOjOhe2Wt_NldXLO3Ly/edit?usp=sharing&ouid=107699434263475311303&rtpof=true&sd=true) elaborado sobre el despliegue en ambiente de pruebas.

**Comment by FelipeVel** [comment]
Se desplegó el api en ambiente de pruebas y se hicieron pruebas sobre el mismo, probando el funcionamiento correcto de sus endpoints.

**Comment by FelipeVel** [comment]
El API se desplegó en producción y en autenticación, dejandolo listo para su uso en cualquiera de los dos ambientes.

**Comment by FelipeVel** [comment]
Se corrigió el rol del api en amazon para políticas en aws
