### ISSUE TITLE
Mantenimiento Modulo de Notificaciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/notificacion_mid#31]
Se requiere realizar mantenimiento a la funcionalidad de notificaciones a nivel de sistema y por correo electrónico.

Actualmente se estan presentando los siguientes errores;

- No llega el link de suscripción por correo electrónico.
- No llega confirmación de suscripción por correo electrónico.
- La validación de suscripción no funciona correctamente ya que pide a usuarios ya suscritos que vuelvan a suscribirse.

**Especificaciones técnicas**

- Las especificaciones técnicas del modulo de notificaciones se encuentra en su [documento técnico](https://drive.google.com/file/d/1ZlXdKAyooyftamyCZX8Btmd5nhDR5YEX/view?usp=sharing) relacionado.

**Sub Tareas**

- [x] Revisión de [documentación existente](https://drive.google.com/file/d/1ZlXdKAyooyftamyCZX8Btmd5nhDR5YEX/view?usp=sharing).
- [x] Revisión de[ pruebas funcionales](https://docs.google.com/spreadsheets/d/1SuAhfDHYM0OxwZ1mrV-MM36aEN5v8Cia/edit?usp=sharing&ouid=104124925692794756698&rtpof=true&sd=true) realizadas.
- [x] Acceder a AWS y revisar funcionamiento del servicio de notificaciones.
- [x] Instalación pruebas del API notificaciones_mid en ambiente local.
- [x] Revisión y análisis de posibles problemas.
- [x] Solución de problemas (desarrollo).

**Criterios de aceptación**

- [x] A cada usuario que no este suscrito a las notificaciones del sistema, le debe llegar un mensaje de suscripción al correo que tiene inscrito en WSo2.
- [x] Cuando el usuario se suscriba mediante el link, su correo debe quedar asociado al topic que maneja el sistema, de tal forma que cuando se ejecute una acción de notificación asociada al topic, se le envie la notificación por correo.
- [x] La suscripción de un usuario debe mantenerse en el tiempo y no caducar, hasta que se indique lo contrario.
- [x] Verificar que las notificaciones internas del sistema esten funcionando correctamente.

**Requerimientos**

- [x] Listado de variables de entorno de notificaciones_mid.
- [x] Usuario con acceso a servicio de notificaciones en AWS.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Usuario con acceso a servicio de notificaciones en AWS.
Usuario: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=52889
Contraseña: consultar con líder técnico

**Comment by a52290451** [comment]
variables de entorno notificacion_mid:

- Name: AWS_DEFAULT_REGION
- Value: us-east-1
- Name: NOTIFICACION_MID_ENVIRONMENT
- Value: test

**Comment by a52290451** [comment]
El API notificacion_mid no tiene dependencias de otras APIs, su única dependencia es con el servicio SNS (Simple Notification Service) en AWS el cual provee la infraestructura necesaria para soportar las notificaciones.

**Comment by JuanCamiloMartinezLopez** [comment]
#### Revisión de documentación existente: 
Se realiza la lectura de la documentación existente, específicamente del manual de usuario.

#### Revisión de pruebas funcionales: 
En las pruebas funcionales no quedó la prueba de la suscripción mediante el endpoint, las suscripciones de prueba fueron realizadas mediante la consola de aws del servicio SNS.

#### Acceder a AWS y revisar funcionamiento del servicio de notificaciones:
Se accede a la consola de AWS de SNS, se revisa configuraciones y declaracion de politicas. 
![image](https://user-images.githubusercontent.com/42418412/235056265-d7b56a98-369e-47fc-a6da-10686cbf16da.png)

#### Instalación pruebas del API notificaciones_mid en ambiente local:

**Comment by JuanCamiloMartinezLopez** [comment]
## Revisión y análisis de posibles problemas.
Se encontraron los siguientes problemas:
- ***Verificar suscripción:*** este endpoint no válida si la suscripción se encuentra pendiente de confirmación
- ***Reenvió del correo de confirmacion de suscripcion:*** Después de tres dias se vence el token de confirmación, por lo que es necesario re enviar este correo para suscribirse a las respuestas.

**Comment by JuanCamiloMartinezLopez** [comment]
### Criterios aceptación
- **A cada usuario que no este suscrito a las notificaciones del sistema, le debe llegar un mensaje de suscripción al correo que tiene inscrito en WSo2.**

![image](https://user-images.githubusercontent.com/42418412/236737503-b11144bc-4711-4ba6-a988-a37bcec830af.png)
![image](https://user-images.githubusercontent.com/42418412/236737542-9edc07c5-0569-40b5-a864-759a4a3bed7b.png)

- **Cuando el usuario se suscriba mediante el link, su correo debe quedar asociado al topic que maneja el sistema, de tal forma que cuando se ejecute una acción de notificación asociada al topic, se le envie la notificación por correo.**

![image](https://user-images.githubusercontent.com/42418412/236737816-4b06a928-fa63-4b7e-814a-0b41e370b217.png)

- **La suscripción de un usuario debe mantenerse en el tiempo y no caducar, hasta que se indique lo contrario.
 Verificar que las notificaciones internas del sistema estén funcionando correctamente.**

Se verifica en la documentación que amenos que el usuario se desuscriba, esta se mantendrá.
