### ISSUE TITLE
Análisis sobre servicios de correo electrónico para implementar notificaciones directas.

### ISSUE THREAD

**Issue by a52290451** [udistrital/notificacion_mid#35]
Se requiere investigar acerca de servicios SMTP gratuitos para el envío de correos electrónicos automáticos, que puedan ser integrados y utilizados a través del modulo de notificaciones o un nuevo microservicio especializado. Esto con el objetivo de eliminar la dependencia actual que existe para el envío y recepción de correos por suscripción en AWS.

**Especificaciones técnicas**

- El servicio SMTP debe ser:
1. Gratuito.
2. Sin limite de envío de correos.
3. Debe poder ser incrustado en un microservicio o consumido a través de comunicación API REST.

**Sub Tareas**

- [x] Investigación de posibles servicios SMTP o similares para el envío de correos.
- [x] Diseño de arquitectura para Módulo de notificaciones por correo electrónico a través de servidor SMTP (considerar clientes, APIs MID, microservicios, servidor y demás elementos involucrados).
- [x] Generar presentación sobre los servicios analizados.

**Criterios de aceptación**

- [x] Se presenta diseño de arquitectura para el módulo de notificaciones por correo electrónico.
- [x] Se presenta la investigación de distintas alternativas de servidores para el envío de correos electrónicas.
- [x] Los servidores que cumplen con los requisitos mencionados.

**Requerimientos**

- No presenta.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
### Opciones para el envió de correos directamente

Se realiza la investigación que cumpla con las características nombradas en el issue, de la cual se plantean las siguientes opciones:

| Opción  	| Descripción                                                                                                                                                                                                                                                          	| Ventajas 	| Desventajas 	| Precio 	| Documentación 	|
|---------	|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|----------	|-------------	|--------	|---------------	|
| SES AWS 	| Amazon SES es un proveedor de servicios de correo electrónico en la nube que se puede integrar en cualquier aplicación para enviar correos electrónicos en bloque. Tanto si envía correos electrónicos de marketing como de transacciones, solo paga por lo que usa. 	| Automatización de transacciones. Fiabilidad. Facil integracion. Permite tener Buzón de correo 	|  Dependencia de la infraestructura de aws         	|     0 USD de 0 a 62 000 correos electrónicos si sale de una instancia EC2, 0,10 USD por 1000 correos electrónicos|         [Documentación](https://aws.amazon.com/es/ses/)      | 
|       Microsoft  Graph Mail	|        Api REST de microsoft que permite el acceso para aplicaciones a las funciones de sus servicio como Outlook                                                                                                                                                                                                                                                            |        Facil integracion. Permite tener Buzón de correo. Todas las funciones integradas de outlook  	|        Dependencia de la infraestructura de Microsoft. Servicio no especializado. SDK no disponible para Golang     	|      Aparentemente gratis, es necesario consultar con Microsoft para el contexto de la Universidad  	|           [ Documentación](https://learn.microsoft.com/en-us/graph/outlook-mail-concept-overview?view=graph-rest-1.0)   	|
|        Open-source email server 	|           Opciones open-source para implementar un servidor con protocolos POP3, IMAP, SMTP para el envio y recepcion de correo, existen varias opciones como IRedMail, Postal, DOVECOT, etc.                                                                                                                                                                                                                                                           	|       Administración completa del  servidor.  	|       Mayor carga para el desarrollo y administración.      	|        El precio vendría de la infraestructura y costos de mantenimiento del servidor	|           Depende de la opción a tomar    	|

**Comment by JuanCamiloMartinezLopez** [comment]
### Presentación 
[Análisis sobre servicios de correo electrónico para implementar.pptx](https://github.com/udistrital/notificacion_mid/files/11883281/Analisis.sobre.servicios.de.correo.electronico.para.implementar.pptx)
![arquitectura_servicio](https://github.com/udistrital/notificacion_mid/assets/42418412/98f5c978-f16a-4b65-a3a7-5104b3169a7a)
