### ISSUE TITLE
Prueba de concepto para SES

### ISSUE THREAD

**Issue by milo19980525** [udistrital/notificacion_mid#38]
Se requiere realizar una prueba de concepto del servicio SES con base en el estudio realizado #35 .

**Especificaciones técnicas**

- La última documentación relacionada con el servicio de notificaciones por correo electrónico se encuentra en #35.

**Sub Tareas**

- [x] Revisar la documentación de implementación de SES en la consola de AWS y en golang mediante su respectivo SDK.
- [x] Implementar la funcionalidad de SES desde la consola de AWS.
- [x] Implementar la funcionalidad de SES desde el api de notificaciones_mid.

**Criterios de aceptación**

- [x] Se realiza la implementación de SES en notificaciones_mid y en la consola de AWS.
- [x] Se documenta el issue con evidencia de implementación e información del uso de SES.

**Requerimientos**

- [x] Acceso al servicio de SES (Hablar con ingeniero de infraestructura).

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
### Verificación de dominio

Se encuentra que el dominio esta registrado como una identidad, pero no se encuentra verificado, se recomienda verificar el dominio para facilitar y mejorar el envió de correos.
![image](https://github.com/udistrital/notificacion_mid/assets/42418412/96da77dc-0d2f-4221-962e-f3c96f536334)

**Comment by JuanCamiloMartinezLopez** [comment]
### prueba de concepto
Se prueba el envió de correos mediante la consola de AWS y mediante el SDK de golang, puesto que el servicio se esta configurando por primera vez este se encuentra en un sandbox para evitar sobre costos, por esto mismo solo se pueden enviar correos a direcciones verificadas, una vez terminado el desarrollo y puesto en producción el servicio esta restricción y otras se eliminarán.
