### ISSUE TITLE
Documentación sobre el API de notificaciones servicio SES

### ISSUE THREAD

**Issue by milo19980525** [udistrital/notificacion_mid#40]
Se requiere documentar los requisitos para poder consumir el api de notificacion_mid, información acerca de la implementación realizada y la configuración de AWS SES.

**Especificaciones técnicas**

- Se consume el servicio SES de AWS para gestionar el envío de correos electrónicos, haciendo peticiones a sus funcionalidades desde el api notifficacion_mid mediante el SDK de golang.
- El desarrollo se encuentra en la rama develop.

**Sub Tareas**

- [ ] Documentar en un archivo word con imágenes y descripción en texto:
- Configuración del servicio SES en AWS.
- Endpoints desarrollados, body, y retorno.

**Criterios de aceptación**

- [ ] Se realiza documento con la información requerida.

**Requerimientos**

- [x] Ninguno

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
### Documento técnico de la funcionalidad de correos con AWS SES

[Documento tecnico Correos AWS SES.pdf](https://github.com/udistrital/notificacion_mid/files/12316985/Documento.tecnico.Correos.AWS.SES.pdf)
